name: Build and Push Docker Image

on:
  push

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-docker-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-docker-

    - name: Build Docker image using Makefile with cached layers
      run: |
        # Define the Docker image name
        DOCKER_IMAGE_NAME=jaxmarl
        # Build the image using the correct context (.) and cached layers
        docker build \
          --cache-from=type=local,src=/tmp/.buildx-cache \
          --cache-to=type=local,dest=/tmp/.buildx-cache,mode=max \
          --push \
          -t ${DOCKER_IMAGE_NAME}:latest \
          .

    - name: Push Docker image to GitHub Container Registry
      run: |
        # Define the Docker image name again
        DOCKER_IMAGE_NAME=jaxmarl
        REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
        # Tag and push the image
        docker tag ${DOCKER_IMAGE_NAME}:latest ghcr.io/${REPO_NAME}:latest
        docker push ghcr.io/${REPO_NAME}:latest
