on:
  push

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx with containerd
      uses: docker/setup-buildx-action@v2
      with:
        install: true
        driver: containerd
        driver-opts: image-store=/var/lib/containerd

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-docker-${{ hashFiles('Dockerfile') }}
        restore-keys: |
          ${{ runner.os }}-docker-

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image using Makefile
      run: |
        # Define the Docker image name here
        DOCKER_IMAGE_NAME=jaxmarl
        # Run the make command to build the Docker image
        make build --progress=plain --builder default \
          --build-arg BUILDKIT_INLINE_CACHE=1 \
          --cache-from type=local,src=/tmp/.buildx-cache \
          --cache-to type=local,dest=/tmp/.buildx-cache,mode=max

    - name: Push Docker image to GitHub Container Registry
      run: |
        # Define the Docker image name again here
        DOCKER_IMAGE_NAME=jaxmarl
        REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
        # Tag and push the image
        docker tag ${DOCKER_IMAGE_NAME}:latest ghcr.io/${REPO_NAME}:latest
        docker push ghcr.io/${REPO_NAME}:latest
